export const FETCHING_STATUS = 'FETCHING_STATUS';
export const FETCHED_STATUS = 'FETCHED_STATUS';
export const UPDATE_HAS_PREFERENCES = 'UPDATE_HAS_PREFERENCES';
export const UPDATE_HAS_CHOSEN = 'UPDATE_HAS_CHOSEN';
